include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
    - linux/**
    - lib/l10n/generated/**
